apiVersion: batch/v1
kind: Job
metadata:
  name: events-microservice-migration
  namespace: bicycle-network
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migration
          image: 628786078121.dkr.ecr.us-east-1.amazonaws.com/events-service:latest
          command: ["python", "-c", "from app.database import create_tables; create_tables()"]
          envFrom:
            - secretRef:
                name: events-microservice-secrets
