apiVersion: apps/v1
kind: Deployment
metadata:
  name: rental-service
  namespace: bicycle-network
  labels:
    app: rental-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rental-service
  template:
    metadata:
      labels:
        app: rental-service
    spec:
      containers:
        - name: rental-service
          image: 628786078121.dkr.ecr.us-east-1.amazonaws.com/rental-service:latest
          ports:
            - containerPort: 8002
          envFrom:
            - secretRef:
                name: rental-service-secrets
          env:
            - name: RUN_MIGRATIONS
              value: "false"
            - name: DISABLE_AUTH
              value: "false"
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              cpu: "256m"
              memory: "512Mi"
            limits:
              cpu: "512m"
              memory: "1Gi"
