#!/bin/bash
# ============================================================
# BikeNet Local Development - Setup Script
# Generates RSA keys and docker-compose.override.yml
# Run this script ONCE before starting docker-compose.
# ============================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
KEYS_DIR="$ROOT_DIR/keys"

# ---- Generate RSA Keys ----
mkdir -p "$KEYS_DIR"

if [ -f "$KEYS_DIR/private.pem" ] && [ -f "$KEYS_DIR/public.pem" ]; then
  echo "✔ RSA keys already exist in $KEYS_DIR"
else
  echo "Generating 2048-bit RSA key pair..."
  openssl genrsa -out "$KEYS_DIR/private.pem" 2048 2>/dev/null
  openssl rsa -in "$KEYS_DIR/private.pem" -pubout -out "$KEYS_DIR/public.pem" 2>/dev/null
  echo "✔ RSA keys generated"
fi

# ---- Read keys ----
PRIVATE_KEY=$(cat "$KEYS_DIR/private.pem")
PUBLIC_KEY=$(cat "$KEYS_DIR/public.pem")

# ---- Generate docker-compose.override.yml with multiline YAML keys ----
OVERRIDE_FILE="$ROOT_DIR/docker-compose.override.yml"

# We need proper YAML indentation for the multiline PEM keys
indent_key() {
  local key="$1"
  local indent="$2"
  echo "$key" | sed "s/^/${indent}/"
}

PRIVATE_KEY_INDENTED=$(indent_key "$PRIVATE_KEY" "          ")
PUBLIC_KEY_INDENTED=$(indent_key "$PUBLIC_KEY" "          ")

cat > "$OVERRIDE_FILE" << YAMLEOF
# ============================================================
# AUTO-GENERATED by scripts/setup.sh — DO NOT EDIT
# Contains RSA keys for JWT signing/verification
# ============================================================
services:
  auth-service:
    environment:
      SECRET_KEY: |-
${PRIVATE_KEY_INDENTED}

  bicycle-service:
    environment:
      JWT_PUBLIC_KEY: |-
${PUBLIC_KEY_INDENTED}

  rental-service:
    environment:
      JWT_PUBLIC_KEY: |-
${PUBLIC_KEY_INDENTED}
YAMLEOF

echo "✔ docker-compose.override.yml generated"

# ---- Generate .env for Google OAuth / Mail credentials ----
ENV_FILE="$ROOT_DIR/.env"

if [ -f "$ENV_FILE" ]; then
  echo "✔ .env file already exists (not overwritten)"
else
  cat > "$ENV_FILE" << 'ENVEOF'
# ============================================================
# BikeNet - Credentials (fill in your real values)
# ============================================================

# Google OAuth2
GOOGLE_CLIENT_ID=your-google-client-id
GOOGLE_CLIENT_SECRET=your-google-client-secret

# Email service
MAIL_USERNAME=test@example.com
MAIL_PASSWORD=testpassword
MAIL_FROM=test@example.com
ENVEOF
  echo "✔ .env file created"
  echo ""
  echo "⚠  IMPORTANT: Edit $ENV_FILE and fill in your Google OAuth credentials:"
  echo "   GOOGLE_CLIENT_ID=..."
  echo "   GOOGLE_CLIENT_SECRET=..."
fi

echo ""
echo "Setup complete! Next steps:"
echo "  1. Edit .env with your Google OAuth and mail credentials"
echo "  2. docker compose up --build"
echo "  3. cd frontend/bicycle-network-frontend && npm install && npm run dev"
echo "  4. Open http://localhost:8080"
