apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rental-service-jero
  namespace: bicycle-network
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: <ACM_CERTIFICATE_ARN>
    alb.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: api.bicycle-network.com
      http:
        paths:
          - path: /rentals
            pathType: Prefix
            backend:
              service:
                name: rental-service-jero
                port:
                  number: 80
