apiVersion: batch/v1
kind: Job
metadata:
  name: rental-service-jero-migration
  namespace: bicycle-network
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migration
          image: 628786078121.dkr.ecr.us-east-1.amazonaws.com/rental-service-jero:latest
          command: ["./rental-service"]
          envFrom:
            - secretRef:
                name: rental-service-jero-secrets
          env:
            - name: RUN_MIGRATIONS
              value: "true"
